{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 「bert-as-serviceで文書ベクトル作成」の動作確認"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n",
      "/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import os\n",
    "import time\n",
    "from bert_serving.server.helper import get_args_parser\n",
    "from bert_serving.server.helper import get_shutdown_parser\n",
    "from bert_serving.server import BertServer\n",
    "from bert_serving.client import BertClient"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "DEBUG = False\n",
    "TEXT_LIST = [\n",
    "    'ロボットは人間に危害を加えてはならない。また、その危険を看過することによって、人間に危害を及ぼしてはならない。',\n",
    "    'ロボットは人間にあたえられた命令に服従しなければならない。ただし、あたえられた命令が、第一条に反する場合は、この限りでない。',\n",
    "    'ロボットは、前掲第一条および第二条に反するおそれのないかぎり、自己をまもらなければならない。',\n",
    "    'すべての人間は、生れながらにして自由であり、かつ、尊厳と権利とについて平等である。',\n",
    "    '人間は、理性と良心とを授けられており、互いに同胞の精神をもって行動しなければならない。',\n",
    "    '「富士〜」で有名な動物園は？',\n",
    "    '富士サファリパークです。',\n",
    "    '東武動物公園です。',\n",
    "    '軽井沢おもちゃ王国です。',\n",
    "    'ロボットは機械です。',\n",
    "]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## サーバ起動"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:__i: 67]:freeze, optimize and export graph, could take a while...\n",
      "I:\u001b[36mGRAPHOPT\u001b[0m:[gra:opt: 52]:model config: /app/model/bert-wiki-ja_config.json\n",
      "I:\u001b[36mGRAPHOPT\u001b[0m:[gra:opt: 55]:checkpoint: /app/model/model.ckpt-1400000\n",
      "I:\u001b[36mGRAPHOPT\u001b[0m:[gra:opt: 59]:build graph...\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34bb7f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34bb7f98>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34bb7f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34bb7f98>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34bb7f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34bb7f98>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34bb7dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34bb7dd8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34ad6d30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34ad6d30>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34ad6d30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34ad6d30>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34a92e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34a92e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34a92e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34a92e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34a92e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34a92e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34c9a4a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34c9a4a8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b15940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b15940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab42ea8e10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab42ea8e10>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3494cc88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3494cc88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3494cc88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3494cc88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3494cc88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3494cc88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34803400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34803400>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34a55668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34a55668>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34ac3710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34ac3710>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3454db70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3454db70>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34803048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34803048>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34583898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34583898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34619320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34619320>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34ac37f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34ac37f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b158d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b158d0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab346199e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab346199e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab346199e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab346199e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab346199e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab346199e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34446a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34446a58>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b158d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b158d0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34a55d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34a55d68>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab344589e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab344589e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab344589e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab344589e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab341ab0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab341ab0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab345b7dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab345b7dd8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab35428710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab35428710>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b158d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b158d0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab340e3400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab340e3400>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab340e3400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab340e3400>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab340e3400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab340e3400>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3401b208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3401b208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b15940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b15940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab35428710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab35428710>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33e63400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33e63400>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33e63400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33e63400>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33e63400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33e63400>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33e8eb00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33e8eb00>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3424b940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3424b940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b15940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b15940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c77668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c77668>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c77668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c77668>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c77668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c77668>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c93c50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c93c50>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c831d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c831d0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3424b940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3424b940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab339fe470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab339fe470>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab339fe470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab339fe470>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab339fe470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab339fe470>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33a877b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33a877b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c80780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c80780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33a422b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33a422b0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab339f95c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab339f95c0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3494c9e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3494c9e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3494c9e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab3494c9e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c93c50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33c93c50>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33dca320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33dca320>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33f20d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33f20d68>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33645f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33645f98>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33645f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33645f98>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33645f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33645f98>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33e8eb00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab33e8eb00>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b92240>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34b92240>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34ac34a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab34ac34a8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab813eb048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fab813eb048>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "I:\u001b[36mGRAPHOPT\u001b[0m:[gra:opt:128]:load parameters from checkpoint...\n",
      "I:\u001b[31mOPTIMIZE_GRAPH\u001b[0m:[gra:opt:130]:visualize model with tensorboard\n",
      "I:\u001b[36mGRAPHOPT\u001b[0m:[gra:opt:138]:optimize...\n",
      "I:\u001b[36mGRAPHOPT\u001b[0m:[gra:opt:146]:freeze...\n",
      "I:\u001b[36mGRAPHOPT\u001b[0m:[gra:opt:151]:write graph to a tmp file: /app/tmp/tmpat4nk8ji\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:__i: 75]:optimized graph is stored at: /app/tmp/tmpat4nk8ji\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:129]:bind all sockets\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:133]:open 8 ventilator-worker sockets\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:136]:start the sink\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "wait until server is ready...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ge:222]:get devices\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ge:255]:device map: \n",
      "\t\tworker  0 -> cpu\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:306]:ready\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:533]:use device cpu, load graph from /app/tmp/tmpat4nk8ji\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loaded a trained SentencePiece model.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:567]:ready and listening!\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:164]:all set, ready to serve request!\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:348]:send config\tclient b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:342]:job register\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#2'\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:576]:new job\tsocket: 0\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#2'\n",
      "W:\u001b[33mWORKER-0\u001b[0m:[ext:con: 64]:\"max_seq_length\" is undefined, and bert config json defines \"max_position_embeddings\"=512. hence set \"max_seq_length\"=30 according to the current batch.\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'TOKENS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#2' (E:0/T:1/A:1)\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:545]:input_ids     \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 30)\n",
      "[[    4     9  4018    11   858    17 14411  5596  8660 17172     8   240\n",
      "      7    65  3657    18 17527  2377 10545     7   858    17 14411  5596\n",
      "     18 20016    32 17172     8     5]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:546]:input_mask    \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 30)\n",
      "[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:547]:input_type_ids\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 30)\n",
      "[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'EMBEDDINGS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#2' (E:1/T:1/A:1)\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:549]:job done\tsize: (1, 768)\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#2'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:357]:send back\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#2'\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:576]:new job\tsocket: 0\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#3'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:342]:job register\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#3'\n",
      "W:\u001b[33mWORKER-0\u001b[0m:[ext:con: 64]:\"max_seq_length\" is undefined, and bert config json defines \"max_position_embeddings\"=512. hence set \"max_seq_length\"=32 according to the current batch.\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'TOKENS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#3' (E:0/T:1/A:1)\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:545]:input_ids     \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 32)\n",
      "[[    4     9  4018    11   858    17 13339   635   551  2174    17 28048\n",
      "   6807     8  3408     7 13339   635   551  2174    12     7   883   702\n",
      "  22285  1308     7    80 10638   278     8     5]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:546]:input_mask    \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 32)\n",
      "[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:547]:input_type_ids\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 32)\n",
      "[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:549]:job done\tsize: (1, 768)\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#3'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'EMBEDDINGS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#3' (E:1/T:1/A:1)\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:357]:send back\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#3'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:342]:job register\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#4'\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:576]:new job\tsocket: 0\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#4'\n",
      "W:\u001b[33mWORKER-0\u001b[0m:[ext:con: 64]:\"max_seq_length\" is undefined, and bert config json defines \"max_position_embeddings\"=512. hence set \"max_seq_length\"=28 according to the current batch.\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'TOKENS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#4' (E:0/T:1/A:1)\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:545]:input_ids     \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 28)\n",
      "[[    4     9  4018    11     7   217 26687   883   702   144  1144   702\n",
      "  22285   220   566    10 16916   845   101     7  2078    18   428    30\n",
      "    154  3427     8     5]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:546]:input_mask    \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 28)\n",
      "[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:547]:input_type_ids\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 28)\n",
      "[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:549]:job done\tsize: (1, 768)\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#4'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'EMBEDDINGS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#4' (E:1/T:1/A:1)\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:357]:send back\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#4'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:342]:job register\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#5'\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:576]:new job\tsocket: 0\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#5'\n",
      "W:\u001b[33mWORKER-0\u001b[0m:[ext:con: 64]:\"max_seq_length\" is undefined, and bert config json defines \"max_position_embeddings\"=512. hence set \"max_seq_length\"=25 according to the current batch.\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'TOKENS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#5' (E:0/T:1/A:1)\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:545]:input_ids     \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 25)\n",
      "[[    4     9  2145   858    11     7   196   964   527  2113  1325    75\n",
      "      7  1368     7  3201  3586    20  3334    20   257 10838    27     8\n",
      "      5]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:546]:input_mask    \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 25)\n",
      "[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:547]:input_type_ids\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 25)\n",
      "[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:549]:job done\tsize: (1, 768)\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#5'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'EMBEDDINGS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#5' (E:1/T:1/A:1)\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:357]:send back\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#5'\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:576]:new job\tsocket: 0\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#6'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:342]:job register\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#6'\n",
      "W:\u001b[33mWORKER-0\u001b[0m:[ext:con: 64]:\"max_seq_length\" is undefined, and bert config json defines \"max_position_embeddings\"=512. hence set \"max_seq_length\"=22 according to the current batch.\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'TOKENS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#6' (E:0/T:1/A:1)\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:545]:input_ids     \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 22)\n",
      "[[    4     9   858    11     7 18570    20   856   509    20    18 15611\n",
      "   8880     7  6109 27717 14647  1806  1216  6807     8     5]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:546]:input_mask    \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 22)\n",
      "[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:547]:input_type_ids\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 22)\n",
      "[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:549]:job done\tsize: (1, 768)\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#6'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'EMBEDDINGS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#6' (E:1/T:1/A:1)\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:357]:send back\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#6'\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:576]:new job\tsocket: 0\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#7'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:342]:job register\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#7'\n",
      "W:\u001b[33mWORKER-0\u001b[0m:[ext:con: 64]:\"max_seq_length\" is undefined, and bert config json defines \"max_position_embeddings\"=512. hence set \"max_seq_length\"=10 according to the current batch.\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'TOKENS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#7' (E:0/T:1/A:1)\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:545]:input_ids     \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 10)\n",
      "[[    4   235  2915 10341    19  3225 12507    11  3017     5]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:546]:input_mask    \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 10)\n",
      "[[1 1 1 1 1 1 1 1 1 1]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:547]:input_type_ids\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 10)\n",
      "[[0 0 0 0 0 0 0 0 0 0]]\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:549]:job done\tsize: (1, 768)\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#7'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'EMBEDDINGS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#7' (E:1/T:1/A:1)\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:357]:send back\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#7'\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:576]:new job\tsocket: 0\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#8'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:342]:job register\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#8'\n",
      "W:\u001b[33mWORKER-0\u001b[0m:[ext:con: 64]:\"max_seq_length\" is undefined, and bert config json defines \"max_position_embeddings\"=512. hence set \"max_seq_length\"=10 according to the current batch.\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'TOKENS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#8' (E:0/T:1/A:1)\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:545]:input_ids     \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 10)\n",
      "[[   4    9 2915  209  726  146 2361 2767    8    5]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:546]:input_mask    \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 10)\n",
      "[[1 1 1 1 1 1 1 1 1 1]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:547]:input_type_ids\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 10)\n",
      "[[0 0 0 0 0 0 0 0 0 0]]\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'EMBEDDINGS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#8' (E:1/T:1/A:1)\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:549]:job done\tsize: (1, 768)\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#8'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:357]:send back\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#8'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:342]:job register\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#9'\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:576]:new job\tsocket: 0\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#9'\n",
      "W:\u001b[33mWORKER-0\u001b[0m:[ext:con: 64]:\"max_seq_length\" is undefined, and bert config json defines \"max_position_embeddings\"=512. hence set \"max_seq_length\"=8 according to the current batch.\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'TOKENS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#9' (E:0/T:1/A:1)\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:545]:input_ids     \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 8)\n",
      "[[    4     9 14419  1408   920  2767     8     5]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:546]:input_mask    \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 8)\n",
      "[[1 1 1 1 1 1 1 1]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:547]:input_type_ids\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 8)\n",
      "[[0 0 0 0 0 0 0 0]]\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:549]:job done\tsize: (1, 768)\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#9'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'EMBEDDINGS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#9' (E:1/T:1/A:1)\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:357]:send back\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#9'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:342]:job register\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#10'\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:576]:new job\tsocket: 0\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#10'\n",
      "W:\u001b[33mWORKER-0\u001b[0m:[ext:con: 64]:\"max_seq_length\" is undefined, and bert config json defines \"max_position_embeddings\"=512. hence set \"max_seq_length\"=8 according to the current batch.\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'TOKENS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#10' (E:0/T:1/A:1)\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:545]:input_ids     \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 8)\n",
      "[[    4     9 25456 25564  1509  2767     8     5]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:546]:input_mask    \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 8)\n",
      "[[1 1 1 1 1 1 1 1]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:547]:input_type_ids\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 8)\n",
      "[[0 0 0 0 0 0 0 0]]\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'EMBEDDINGS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#10' (E:1/T:1/A:1)\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:549]:job done\tsize: (1, 768)\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#10'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:357]:send back\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#10'\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:gen:576]:new job\tsocket: 0\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#11'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:342]:job register\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#11'\n",
      "W:\u001b[33mWORKER-0\u001b[0m:[ext:con: 64]:\"max_seq_length\" is undefined, and bert config json defines \"max_position_embeddings\"=512. hence set \"max_seq_length\"=8 according to the current batch.\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'TOKENS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#11' (E:0/T:1/A:1)\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:545]:input_ids     \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 8)\n",
      "[[   4    9 4018   11 1869 2767    8    5]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:546]:input_mask    \n",
      "<class 'numpy.ndarray'>\n",
      "(1, 8)\n",
      "[[1 1 1 1 1 1 1 1]]\n",
      "I:\u001b[31mESTIMATOR\u001b[0m:[__i:_ru:547]:input_type_ids\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 8)\n",
      "[[0 0 0 0 0 0 0 0]]\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:_ru:549]:job done\tsize: (1, 768)\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#11'\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:334]:collect b'EMBEDDINGS' b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#11' (E:1/T:1/A:1)\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:_ru:357]:send back\tsize: 1\tjob id: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb#11'\n"
     ]
    }
   ],
   "source": [
    "os.environ['ZEROMQ_SOCK_TMP_DIR'] = '/app/tmp'\n",
    "args = get_args_parser().parse_args([\n",
    "    '-model_dir', '/app/model',\n",
    "    '-ckpt_name', 'model.ckpt-1400000',\n",
    "    '-config_name', 'bert-wiki-ja_config.json',\n",
    "    '-graph_tmp_dir', '/app/tmp',\n",
    "    '-port', '5555',\n",
    "    '-port_out', '5556',\n",
    "    '-max_seq_len', 'NONE',\n",
    "    '-num_worker', '1',\n",
    "    '-cpu',\n",
    "    '-show_tokens_to_client',\n",
    "])\n",
    "server = BertServer(args)\n",
    "server.start()\n",
    "\n",
    "print('wait until server is ready...')\n",
    "time.sleep(20)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 文書ベクトル取得"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:180]:new config request\treq id: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "/usr/local/lib/python3.6/dist-packages/bert_serving_client-1.9.5-py3.6.egg/bert_serving/client/__init__.py:290: UserWarning: server does not put a restriction on \"max_seq_len\", it will determine \"max_seq_len\" dynamically according to the sequences in the batch. you can restrict the sequence length on the client side for better efficiency\n",
      "  warnings.warn('server does not put a restriction on \"max_seq_len\", '\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:196]:new encode request\treq id: 2\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:196]:new encode request\treq id: 3\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:196]:new encode request\treq id: 4\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:196]:new encode request\treq id: 5\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:196]:new encode request\treq id: 6\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:196]:new encode request\treq id: 7\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:196]:new encode request\treq id: 8\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:196]:new encode request\treq id: 9\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:196]:new encode request\treq id: 10\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:196]:new encode request\treq id: 11\tsize: 1\tclient: b'199b2030-0372-4a4e-93c1-9ce37e50d7cb'\n"
     ]
    }
   ],
   "source": [
    "bc = BertClient()\n",
    "doc_vecs = []\n",
    "for text in TEXT_LIST:\n",
    "    result = bc.encode([text], show_tokens=True)\n",
    "    embeddings = result[0][0]\n",
    "    tokens = result[1][0]\n",
    "    doc_vecs.append(embeddings)\n",
    "\n",
    "    if DEBUG:\n",
    "        print('########################################')\n",
    "        print('text        :', text)\n",
    "        print('tokens      :', tokens)\n",
    "        print('len(tokens) :', len(tokens))\n",
    "        print('type        :', type(embeddings))\n",
    "        print('shape       :', embeddings.shape)\n",
    "        print('norm        :', np.linalg.norm(embeddings))\n",
    "        print('embeddings  :', '[', embeddings[0], embeddings[1], '...', embeddings[-2], embeddings[-1], ']')\n",
    "        print()\n",
    "bc.close()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## サーバ停止"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:clo: 89]:shutting down...\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:clo:274]:shutting down...\n",
      "I:\u001b[32mSINK\u001b[0m:[__i:clo:279]:terminated!\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:clo:480]:shutting down...\n",
      "I:\u001b[33mWORKER-0\u001b[0m:[__i:clo:485]:terminated!\n",
      "I:\u001b[35mVENTILATOR\u001b[0m:[__i:_ru:219]:terminated!\n"
     ]
    }
   ],
   "source": [
    "server.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.0000 : ロボットは人間に危害を加えてはならない。また、その危険を看過することによって、人間に危害を及ぼしてはならない。\n",
      "0.9205 : ロボットは人間にあたえられた命令に服従しなければならない。ただし、あたえられた命令が、第一条に反する場合は、この限りでない。\n",
      "0.8995 : ロボットは、前掲第一条および第二条に反するおそれのないかぎり、自己をまもらなければならない。\n",
      "0.8914 : 人間は、理性と良心とを授けられており、互いに同胞の精神をもって行動しなければならない。\n",
      "0.8719 : すべての人間は、生れながらにして自由であり、かつ、尊厳と権利とについて平等である。\n",
      "0.8482 : ロボットは機械です。\n",
      "0.8270 : 「富士〜」で有名な動物園は？\n",
      "0.8017 : 東武動物公園です。\n",
      "0.7916 : 軽井沢おもちゃ王国です。\n",
      "0.7887 : 富士サファリパークです。\n"
     ]
    }
   ],
   "source": [
    "query_vec = doc_vecs[0]\n",
    "score = np.sum(query_vec * doc_vecs, axis=1) / np.linalg.norm(doc_vecs, axis=1) / np.linalg.norm(query_vec)\n",
    "topk_idx = np.argsort(score)[::-1]\n",
    "for idx in topk_idx:\n",
    "    print('{:6.4f} : {}'.format(score[idx], TEXT_LIST[idx]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
